spring:
    application:
        name: etudient-service
        profiles: { active: dev }

    r2dbc:
        url: r2dbc:postgresql://localhost:5432/etudiant_db
        username: postgres
        password: sadik2003

    dotenv:
        enabled: true

    cloud:
        config:
            enabled: false

server:
    port: 8083